CREATE DATABASE IF NOT EXISTS triptool;
USE triptool;

CREATE TABLE IF NOT EXISTS Member (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  password BINARY(60) NOT NULL,
  email VARCHAR(50) NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Trip (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  member_id INT(6) UNSIGNED NOT NULL,
  title VARCHAR(50) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  destination VARCHAR(50) NOT NULL
);

ALTER TABLE Trip ADD CONSTRAINT member_fk FOREIGN KEY (member_id) REFERENCES Member(id);