CREATE DATABASE IF NOT EXISTS triptool;
USE triptool;

CREATE TABLE IF NOT EXISTS Member (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  password BINARY(60) NOT NULL,
  email VARCHAR(50) NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Trip (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  destination VARCHAR(255) NOT NULL,
  dateStart TIMESTAMP NOT NULL,
  dateEnd TIMESTAMP NOT NULL
);
